config/routes.rb
Rails.application.routes.draw do
 
  root 'posts#index', as: 'home'

  get 'register' => 'users#new'
  get 'posts' => 'posts#posts'
  resources :users, except: [:new]

  get 'about' => 'pages#about', as: 'about'

  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create', as: 'login_user'
  delete 'logout' => 'sessions#destroy', as: 'logout'

  resources :posts, except: [:posts] do 
    resources :comments
  end

  resources :categories, except: [:destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Omedale Blog", home_path, class: "navbar-brand", id: "logo" %> 
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", home_path %></li>
          </ul>
          <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
          <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
          <li><%= link_to "Create Post", new_post_path %></li>
          <% end %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
          <% if logged_in? %>
              <li><%= link_to "My Account", user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Add Categories", '/categories/new' %></li>
              <li><%= link_to "Update Account", edit_user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log Out", logout_path, method: :delete %></li>
          <% else %>
              <li><%= link_to "Login", '/login' %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Register", register_path %></li>
          <% end %>
          </ul>
        </li>
        </ul>
        </div>
      </div>
    </nav>
    <div class="container">
        <%= yield %>
    </div>
    
    <div class="container">
    <footer class="footer">
    <small>
    Copyright © <a href="#">The Complete Ruby on Rails Developer</a>
    by <a href="#">Omedale</a>
    </small>
    <nav>
    <ul>
    <li><%= link_to "About", about_path %></li>
    </ul>
    </nav>
    </footer>  
    </div>
  </body>
</html>